import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.atn.PredictionMode;
import org.antlr.v4.runtime.misc.TestRig;

import java.io.IOException;

/**
 * Created by xuyong on 2015/12/2.
 */
public class Main {
    public static void main(String [] args) throws IOException {
        System.out.println("test");
        String filename="C:\\Users\\xuyong\\Documents\\Dropbox\\course\\compilers\\MiniJava_Compiler\\src\\test\\testfiles\\factorial.java";
        ANTLRFileStream in = new ANTLRFileStream(filename);
        //use lexer and parser class generated by antlr
        MiniJavaLexer lexer = new MiniJavaLexer(in);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        MiniJavaParser parser = new MiniJavaParser(tokens);
        String treestring=parser.goal().toStringTree();
        System.out.println(treestring);

    }

}
